// Code generated by goapigen. DO NOT EDIT.
package domain

import (
	"time"
	
)


// Order represents a Order object
type Order struct {
	// When the order was placed
	CreatedAt time.Time `bson:"created_at" json:"created_at" validate:"format=date-time"`
	// Unique identifier for the order
	ID string `bson:"id" json:"id" validate:"format=uuid"`
	// ID of the pet being ordered
	PetId string `bson:"pet_id" json:"pet_id" validate:"required,format=uuid"`
	// Number of pets ordered
	Quantity int32 `bson:"quantity" json:"quantity" validate:"required,min=1"`
	// Order status
	Status string `bson:"status" json:"status" validate:"enum=placed approved delivered"`
	// When the order was last updated
	UpdatedAt time.Time `bson:"updated_at" json:"updated_at" validate:"format=date-time"`
	
}

// Pet represents a Pet object
type Pet struct {
	// Age of the pet in years
	Age int32 `bson:"age" json:"age"`
	// When the pet was added to the system
	CreatedAt time.Time `bson:"created_at" json:"created_at" validate:"format=date-time"`
	// Unique identifier for the pet
	ID string `bson:"id" json:"id" validate:"format=uuid"`
	// Name of the pet
	Name string `bson:"name" json:"name" validate:"required,min=1,max=100"`
	// Species of the pet
	Species string `bson:"species" json:"species"`
	// Status of the pet
	Status string `bson:"status" json:"status" validate:"required,enum=available pending sold"`
	// When the pet was last updated
	UpdatedAt time.Time `bson:"updated_at" json:"updated_at" validate:"format=date-time"`
	
}
 